import type { ArchitecturalTemplate } from "./types";

/** Casa en L — 3 dormitorios, living generoso, patio inferior (100 m² típico). */
export const L_SHAPE_FAMILY_3BED: ArchitecturalTemplate = {
  id: "l_shape_family_3bed",
  label: "Casa en L familiar",
  shape: "l_shape",
  targetBedrooms: 3,
  targetBathrooms: 1,
  canvas: { width: 400, height: 400 },
  lVoidUpperRight: true,
  slots: [
    {
      slotId: "access",
      group: "access",
      acceptedRoomIds: ["ACCESO", "RECIBIDOR", "HALL"],
      x: 24,
      y: 208,
      width: 56,
      height: 64,
    },
    {
      slotId: "social_main",
      group: "social",
      acceptedRoomIds: [
        "SALA_COMEDOR",
        "LIVING_COMEDOR",
        "ESTANCIA_COMEDOR_COCINA",
        "LIVING",
        "COMEDOR",
      ],
      x: 80,
      y: 208,
      width: 120,
      height: 80,
    },
    {
      slotId: "kitchen",
      group: "service",
      acceptedRoomIds: ["COCINA"],
      x: 208,
      y: 208,
      width: 72,
      height: 80,
    },
    {
      slotId: "private_bed_1",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_1", "DORMITORIO_PRINCIPAL", "SUITE"],
      x: 128,
      y: 24,
      width: 68,
      height: 80,
    },
    {
      slotId: "private_bed_2",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_2"],
      x: 128,
      y: 104,
      width: 68,
      height: 72,
    },
    {
      slotId: "private_bed_3",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_3"],
      x: 16,
      y: 24,
      width: 104,
      height: 80,
    },
    {
      slotId: "bath",
      group: "service",
      acceptedRoomIds: ["BANIO_PRINCIPAL", "BANO", "BAÑO", "BANIO"],
      x: 16,
      y: 104,
      width: 56,
      height: 48,
    },
    {
      slotId: "distributor",
      group: "circulation",
      acceptedRoomIds: ["DISTRIBUIDOR", "PASILLO", "CIRCULACION"],
      x: 72,
      y: 104,
      width: 56,
      height: 48,
    },
    {
      slotId: "patio",
      group: "outdoor",
      acceptedRoomIds: [
        "PATIO",
        "PATIO_INTERIOR",
        "PATIO_CON_PARRILLA",
        "JARDIN",
      ],
      x: 24,
      y: 296,
      width: 352,
      height: 80,
    },
  ],
  defaultDoors: [
    { slotId: "access", side: "east", connectsToSlotId: "social_main" },
    { slotId: "social_main", side: "east", connectsToSlotId: "kitchen" },
    { slotId: "social_main", side: "north", connectsToSlotId: "distributor" },
    { slotId: "distributor", side: "east", connectsToSlotId: "private_bed_1" },
    { slotId: "distributor", side: "east", connectsToSlotId: "private_bed_2" },
    { slotId: "distributor", side: "west", connectsToSlotId: "private_bed_3" },
    { slotId: "distributor", side: "west", connectsToSlotId: "bath" },
    { slotId: "social_main", side: "south", connectsToSlotId: "patio" },
  ],
  defaultWindows: [
    { slotId: "social_main", side: "south", position: 0.5 },
    { slotId: "private_bed_1", side: "north", position: 0.5 },
    { slotId: "private_bed_3", side: "west", position: 0.5 },
    { slotId: "kitchen", side: "east", position: 0.5 },
  ],
  furnitureHints: [
    { slotId: "social_main", kind: "sofa" },
    { slotId: "social_main", kind: "table" },
    { slotId: "kitchen", kind: "counter" },
    { slotId: "private_bed_1", kind: "bed" },
    { slotId: "private_bed_2", kind: "bed" },
    { slotId: "private_bed_3", kind: "bed" },
    { slotId: "bath", kind: "wc" },
  ],
  hardAdjacencies: [
    { fromSlotId: "social_main", toSlotId: "kitchen" },
    { fromSlotId: "social_main", toSlotId: "patio" },
    { fromSlotId: "distributor", toSlotId: "private_bed_1" },
    { fromSlotId: "distributor", toSlotId: "private_bed_2" },
    { fromSlotId: "distributor", toSlotId: "private_bed_3" },
    { fromSlotId: "distributor", toSlotId: "bath" },
  ],
  softAdjacencies: [
    { fromSlotId: "private_bed_1", toSlotId: "bath", note: "cerca del núcleo húmedo" },
    { fromSlotId: "social_main", toSlotId: "bath" },
    { fromSlotId: "kitchen", toSlotId: "patio", note: "ventilación cocina-patio" },
  ],
};

/** 2 dormitorios + patio trasero — lote rectangular compacto. */
export const COMPACT_2BED_PATIO: ArchitecturalTemplate = {
  id: "compact_2bed_patio",
  label: "Compacta 2 dorm + patio",
  shape: "rectangular",
  targetBedrooms: 2,
  targetBathrooms: 1,
  canvas: { width: 640, height: 400 },
  slots: [
    {
      slotId: "access",
      group: "access",
      acceptedRoomIds: ["ACCESO", "RECIBIDOR"],
      x: 16,
      y: 300,
      width: 72,
      height: 84,
    },
    {
      slotId: "social_main",
      group: "social",
      acceptedRoomIds: ["SALA_COMEDOR", "LIVING_COMEDOR", "LIVING", "COMEDOR"],
      x: 88,
      y: 200,
      width: 280,
      height: 184,
    },
    {
      slotId: "kitchen",
      group: "service",
      acceptedRoomIds: ["COCINA"],
      x: 368,
      y: 200,
      width: 120,
      height: 120,
    },
    {
      slotId: "private_bed_1",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_1", "DORMITORIO_PRINCIPAL"],
      x: 368,
      y: 48,
      width: 120,
      height: 144,
    },
    {
      slotId: "private_bed_2",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_2"],
      x: 496,
      y: 48,
      width: 128,
      height: 144,
    },
    {
      slotId: "bath",
      group: "service",
      acceptedRoomIds: ["BANIO_PRINCIPAL", "BANO", "BAÑO", "BANIO"],
      x: 496,
      y: 200,
      width: 128,
      height: 72,
    },
    {
      slotId: "distributor",
      group: "circulation",
      acceptedRoomIds: ["DISTRIBUIDOR", "PASILLO"],
      x: 368,
      y: 328,
      width: 120,
      height: 56,
    },
    {
      slotId: "patio",
      group: "outdoor",
      acceptedRoomIds: ["PATIO", "PATIO_INTERIOR", "JARDIN"],
      x: 88,
      y: 16,
      width: 400,
      height: 168,
    },
  ],
  defaultDoors: [
    { slotId: "access", side: "north", connectsToSlotId: "social_main" },
    { slotId: "social_main", side: "east", connectsToSlotId: "kitchen" },
    { slotId: "social_main", side: "north", connectsToSlotId: "patio" },
    { slotId: "distributor", side: "north", connectsToSlotId: "private_bed_1" },
    { slotId: "distributor", side: "east", connectsToSlotId: "bath" },
  ],
  defaultWindows: [
    { slotId: "social_main", side: "west", position: 0.4 },
    { slotId: "patio", side: "north", position: 0.5 },
    { slotId: "private_bed_2", side: "east", position: 0.5 },
  ],
  furnitureHints: [
    { slotId: "social_main", kind: "sofa" },
    { slotId: "kitchen", kind: "counter" },
    { slotId: "private_bed_1", kind: "bed" },
    { slotId: "private_bed_2", kind: "bed" },
  ],
  hardAdjacencies: [
    { fromSlotId: "social_main", toSlotId: "kitchen" },
    { fromSlotId: "social_main", toSlotId: "patio" },
    { fromSlotId: "distributor", toSlotId: "private_bed_1" },
    { fromSlotId: "distributor", toSlotId: "bath" },
  ],
  softAdjacencies: [
    { fromSlotId: "private_bed_2", toSlotId: "bath" },
    { fromSlotId: "kitchen", toSlotId: "patio" },
  ],
};

/** Lote angosto — circulación lineal, ambientes apilados. */
export const NARROW_LOT_LINEAR: ArchitecturalTemplate = {
  id: "narrow_lot_linear",
  label: "Lote angosto lineal",
  shape: "rectangular",
  targetBedrooms: 2,
  canvas: { width: 360, height: 520 },
  slots: [
    {
      slotId: "access",
      group: "access",
      acceptedRoomIds: ["ACCESO", "RECIBIDOR"],
      x: 24,
      y: 440,
      width: 80,
      height: 64,
    },
    {
      slotId: "social_main",
      group: "social",
      acceptedRoomIds: ["SALA_COMEDOR", "LIVING", "COMEDOR"],
      x: 24,
      y: 300,
      width: 312,
      height: 128,
    },
    {
      slotId: "kitchen",
      group: "service",
      acceptedRoomIds: ["COCINA"],
      x: 24,
      y: 200,
      width: 152,
      height: 92,
    },
    {
      slotId: "distributor",
      group: "circulation",
      acceptedRoomIds: ["DISTRIBUIDOR", "PASILLO"],
      x: 176,
      y: 200,
      width: 72,
      height: 92,
    },
    {
      slotId: "private_bed_1",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_1", "DORMITORIO_PRINCIPAL"],
      x: 24,
      y: 96,
      width: 152,
      height: 96,
    },
    {
      slotId: "private_bed_2",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_2", "DORMITORIO_3"],
      x: 184,
      y: 96,
      width: 152,
      height: 96,
    },
    {
      slotId: "bath",
      group: "service",
      acceptedRoomIds: ["BANIO_PRINCIPAL", "BANO", "BAÑO", "BANIO"],
      x: 248,
      y: 200,
      width: 88,
      height: 92,
    },
    {
      slotId: "patio",
      group: "outdoor",
      acceptedRoomIds: ["PATIO", "PATIO_INTERIOR"],
      x: 24,
      y: 16,
      width: 312,
      height: 72,
    },
  ],
  defaultDoors: [
    { slotId: "access", side: "north", connectsToSlotId: "social_main" },
    { slotId: "social_main", side: "north", connectsToSlotId: "kitchen" },
    { slotId: "distributor", side: "west", connectsToSlotId: "private_bed_1" },
    { slotId: "distributor", side: "east", connectsToSlotId: "private_bed_2" },
    { slotId: "distributor", side: "south", connectsToSlotId: "bath" },
  ],
  defaultWindows: [
    { slotId: "social_main", side: "west", position: 0.5 },
    { slotId: "patio", side: "north", position: 0.5 },
  ],
  furnitureHints: [
    { slotId: "social_main", kind: "sofa" },
    { slotId: "kitchen", kind: "counter" },
    { slotId: "private_bed_1", kind: "bed" },
  ],
  hardAdjacencies: [
    { fromSlotId: "social_main", toSlotId: "kitchen" },
    { fromSlotId: "distributor", toSlotId: "private_bed_1" },
    { fromSlotId: "distributor", toSlotId: "bath" },
  ],
  softAdjacencies: [
    { fromSlotId: "social_main", toSlotId: "patio" },
    { fromSlotId: "private_bed_2", toSlotId: "bath" },
  ],
};

/** Patio central como corazón del plano — planta cuadrada. */
export const PATIO_CENTRAL: ArchitecturalTemplate = {
  id: "patio_central",
  label: "Patio central",
  shape: "square",
  targetBedrooms: 3,
  canvas: { width: 520, height: 520 },
  slots: [
    {
      slotId: "access",
      group: "access",
      acceptedRoomIds: ["ACCESO"],
      x: 208,
      y: 432,
      width: 104,
      height: 72,
    },
    {
      slotId: "social_main",
      group: "social",
      acceptedRoomIds: ["SALA_COMEDOR", "LIVING_COMEDOR", "LIVING"],
      x: 32,
      y: 280,
      width: 176,
      height: 144,
    },
    {
      slotId: "kitchen",
      group: "service",
      acceptedRoomIds: ["COCINA"],
      x: 312,
      y: 280,
      width: 176,
      height: 144,
    },
    {
      slotId: "patio",
      group: "outdoor",
      acceptedRoomIds: ["PATIO", "PATIO_INTERIOR", "PATIO_CENTRAL"],
      x: 176,
      y: 176,
      width: 168,
      height: 168,
    },
    {
      slotId: "private_bed_1",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_1", "DORMITORIO_PRINCIPAL"],
      x: 32,
      y: 32,
      width: 176,
      height: 136,
    },
    {
      slotId: "private_bed_2",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_2"],
      x: 312,
      y: 32,
      width: 176,
      height: 136,
    },
    {
      slotId: "private_bed_3",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_3"],
      x: 208,
      y: 32,
      width: 104,
      height: 136,
    },
    {
      slotId: "bath",
      group: "service",
      acceptedRoomIds: ["BANIO_PRINCIPAL", "BANO", "BAÑO"],
      x: 208,
      y: 360,
      width: 104,
      height: 64,
    },
    {
      slotId: "distributor",
      group: "circulation",
      acceptedRoomIds: ["DISTRIBUIDOR", "PASILLO"],
      x: 208,
      y: 280,
      width: 104,
      height: 72,
    },
  ],
  defaultDoors: [
    { slotId: "social_main", side: "east", connectsToSlotId: "patio" },
    { slotId: "kitchen", side: "west", connectsToSlotId: "patio" },
    { slotId: "distributor", side: "north", connectsToSlotId: "patio" },
    { slotId: "access", side: "north", connectsToSlotId: "distributor" },
  ],
  defaultWindows: [
    { slotId: "private_bed_1", side: "west", position: 0.5 },
    { slotId: "private_bed_2", side: "east", position: 0.5 },
    { slotId: "patio", side: "north", position: 0.5 },
  ],
  furnitureHints: [
    { slotId: "social_main", kind: "sofa" },
    { slotId: "patio", kind: "table" },
  ],
  hardAdjacencies: [
    { fromSlotId: "social_main", toSlotId: "patio" },
    { fromSlotId: "kitchen", toSlotId: "patio" },
    { fromSlotId: "distributor", toSlotId: "patio" },
  ],
  softAdjacencies: [
    { fromSlotId: "private_bed_1", toSlotId: "bath" },
    { fromSlotId: "social_main", toSlotId: "kitchen" },
  ],
};

/** Casa fin de semana — galería lateral + parrilla. */
export const WEEKEND_GALLERY_HOUSE: ArchitecturalTemplate = {
  id: "weekend_gallery_house",
  label: "Fin de semana con galería",
  shape: "rectangular",
  targetBedrooms: 2,
  canvas: { width: 720, height: 440 },
  slots: [
    {
      slotId: "access",
      group: "access",
      acceptedRoomIds: ["ACCESO"],
      x: 24,
      y: 320,
      width: 64,
      height: 96,
    },
    {
      slotId: "social_main",
      group: "social",
      acceptedRoomIds: ["SALA_COMEDOR", "LIVING", "GALERIA", "GALERÍA"],
      x: 88,
      y: 200,
      width: 320,
      height: 216,
    },
    {
      slotId: "kitchen",
      group: "service",
      acceptedRoomIds: ["COCINA"],
      x: 408,
      y: 200,
      width: 128,
      height: 128,
    },
    {
      slotId: "gallery",
      group: "outdoor",
      acceptedRoomIds: ["GALERIA", "GALERÍA", "QUINCHO"],
      x: 544,
      y: 120,
      width: 152,
      height: 296,
    },
    {
      slotId: "patio",
      group: "outdoor",
      acceptedRoomIds: [
        "PATIO",
        "PATIO_CON_PARRILLA",
        "PARRILLA",
        "PATIO_EXTERIOR",
      ],
      x: 408,
      y: 24,
      width: 288,
      height: 88,
    },
    {
      slotId: "private_bed_1",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_1", "DORMITORIO_PRINCIPAL"],
      x: 88,
      y: 24,
      width: 144,
      height: 168,
    },
    {
      slotId: "private_bed_2",
      group: "private",
      acceptedRoomIds: ["DORMITORIO_2"],
      x: 240,
      y: 24,
      width: 144,
      height: 168,
    },
    {
      slotId: "bath",
      group: "service",
      acceptedRoomIds: ["BANIO_PRINCIPAL", "BANO", "BAÑO"],
      x: 408,
      y: 336,
      width: 128,
      height: 80,
    },
    {
      slotId: "distributor",
      group: "circulation",
      acceptedRoomIds: ["DISTRIBUIDOR", "PASILLO"],
      x: 384,
      y: 328,
      width: 24,
      height: 88,
    },
  ],
  defaultDoors: [
    { slotId: "access", side: "north", connectsToSlotId: "social_main" },
    { slotId: "social_main", side: "east", connectsToSlotId: "gallery" },
    { slotId: "social_main", side: "north", connectsToSlotId: "patio" },
    { slotId: "kitchen", side: "north", connectsToSlotId: "patio" },
  ],
  defaultWindows: [
    { slotId: "social_main", side: "west", position: 0.35 },
    { slotId: "gallery", side: "east", position: 0.5 },
    { slotId: "patio", side: "north", position: 0.5 },
  ],
  furnitureHints: [
    { slotId: "social_main", kind: "sofa" },
    { slotId: "gallery", kind: "table" },
    { slotId: "patio", kind: "table" },
  ],
  hardAdjacencies: [
    { fromSlotId: "social_main", toSlotId: "kitchen" },
    { fromSlotId: "social_main", toSlotId: "patio" },
    { fromSlotId: "social_main", toSlotId: "gallery" },
  ],
  softAdjacencies: [
    { fromSlotId: "kitchen", toSlotId: "patio" },
    { fromSlotId: "private_bed_1", toSlotId: "bath" },
  ],
};

export const ARCHITECTURAL_TEMPLATES: ArchitecturalTemplate[] = [
  L_SHAPE_FAMILY_3BED,
  COMPACT_2BED_PATIO,
  NARROW_LOT_LINEAR,
  PATIO_CENTRAL,
  WEEKEND_GALLERY_HOUSE,
];

export const TEMPLATE_BY_ID = Object.fromEntries(
  ARCHITECTURAL_TEMPLATES.map((t) => [t.id, t]),
) as Record<string, ArchitecturalTemplate>;
